architecture/providers_database_architecture.md
architecture/providers_database_architecture/hardware.md
architecture/providers_database_architecture/host.md

Adding openstack host model doc, describing what collumns
will be filled by attributes available from OpenStack Ironic
service.

Add OpenStack host model doc

---

.haml-lint.yml

The miq_bot will also lint haml files and it needs a config file.
For now the haml-lint will use a symlink to .rubocop.yml, but this can change in the future.

Created .haml-lint.yml for miq_bot's upcoming haml-lint feature

---

external_auth.md

Update to the external authentication guide to mention the new --ipadomain when installing IPA from the CLI.

Update to the external authentication guide to mention the new --ipadomain option.

---

miq-dev-appliance-setup/MAC/on_appliance/defines.sh
miq-dev-appliance-setup/MAC/on_appliance/map-source.sh
miq-dev-appliance-setup/MAC/on_appliance/source-updated.sh

Modified scripts to prevent generated data from being stored on
the MAC via shared folders.

Store generated data locally on the appliance.

---

README.md
developer_copr_setup_centos6.md

Moved a private wiki page to the guides repo.
Note, we'll need to convert this to use centos7 as have examples we need to package for 7.
@abellotti @carbonin Please review

Add copr guide for packaging upstream centos6 rpms.

---

developer_setup.md

Updated `bundle install` command, since we removed Qpid support: https://github.com/ManageIQ/manageiq/pull/4291
@jrafanie

Updated bundle command after removed qpid support

---

developer_setup.md

Homebrew installs the database as `postgres`. So creating the `root` user needs to run as the postgres database. The Homebrew user is has enough rights to create the role, but psql will not find a `whoami` database to connect to, while the `postgres`one is always there.

Add some additional hints for OS/X

---

README.md
developer_setup.md
developer_setup/running_test_suites.md

I've tweaked the server startup doc to be a bit more clear and added a doc page on running the test suites.
Suggestions welcome, especially for the Self Service setup as I just made that up quickly without looking too closely at the runner.

Test suite doc; tweaks

---

coding_style_and_standards.md
developer_setup/minimal_mode.md

without the blank line the bullet points are rendered inline.
See http://manageiq.org/documentation/development/coding_style_and_standards/#error-and-issue-reporting

Fix rendering of bullet points in the coding style section

---

developer_setup.md

We had a situation today where `bin/setup` failed to load the sprockets gem. It turned out that it could not use the babel gem. Installig nodejs solved the issue.
@himdel found the solution, which got verified by @mattmahoneyrh

Mention node.js as JS runtime

---

developer_setup.md

MiQ now needs at least ruby 2.2.2, so mention it in the guide.

Require ruby 2.2.2

---

developer_setup.md

A couple "Configure PostgreSQL" commands didn't work as-is; clarified where password is asked.
rbenv install 2.2.0 gives an obscure linker warning fixed by having `libffi-devel` [https://github.com/rbenv/ruby-build/issues/690].
Their FAQ actually suggests more [https://github.com/rbenv/ruby-build/wiki#suggested-build-environment]:
dnf install -y gcc bzip2 openssl-devel libyaml-devel libffi-devel readline-devel zlib-devel gdbm-devel ncurses-devel
but `bzip2 libffi-devel readline-devel` (plus `openssl-devel` we already listed) were enough to build.
(not sure if these are relevant for rvm/ruby-install, or for Ruby 2.2.1+, but as long as guide says "required version is 2.2", it should work with 2.2.0)
nodejs is the obvious option to satisfy ExecJS, otherwise sprockets/es6 gem refuses to load. …

developer_setup.md: fix some steps and deps - tested on clean Centos 7.1

---

developer_setup.md

Purpose of this command is not to rewrite the `pg_hba.conf` if there is already a record for the local. However, it doesn't work as expected because the grep fails all the time when running without the sudo.
All in all, it kind of works (not as supposed), but it produces this err msg:
```bash
[jkremser@dhcp-10-40-1-43 manageiq master]λ grep -q '^local\s' /var/lib/pgsql/data/pg_hba.conf || echo "local all all trust" | sudo tee /var/lib/pgsql/data/pg_hba.conf
grep: /var/lib/pgsql/data/pg_hba.conf: Permission denied
```

Grepping /var/lib/pgsql/data/pg_hba.conf w/o sudo fails with Permission denied

---

.rubocop.yml

Some changes were made to the configuration options between 0.34 and
0.37 that made the current .rubocop.yml invalid.
***
Accompanies https://github.com/ManageIQ/manageiq/pull/6866

Update rubocop config to be v0.37+ compatible

---

developer_setup.md

rugged needs cmake to create the native part and cmake is not installed on os/x by default.

Add cmake to packages to be installed from brew for rugged gem

---

developer_setup.md

Before, this command would have overwritten the entire pg_hba.conf file if you did not have a matching line.
With the -a flag tee will append the line to the end of the file rather than truncating it.
Introduced in #102
@jrafanie @bdunne

Add -a flag to tee command for pg_hba.conf

---

developer_setup.md

In RPM distributions like CentOS and Fedora the "npm" package is separate, and
not installed by default when Node.js is installed. As a result the execution
of the "bin/setup" will fail if the instructions are followed to setup the
environment from scratch, because it uses the "npm" command to install bower.
This patch changes the instructions so that the "npm" package is also
installed.
Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>

Install "npm" in CentOS and Fedora

---

developer_setup.md

Currently the installation of bower is done by the "bin/setup" script,
but this will fail if executed with a non-privileged and the Node.js and
NPM installation was performed by a privileged user. To avoid that
issue, this patch changes the documentation to instruct the user to
install bower manually, with a privileged user.
Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>

Install bower manually with root

---

.rubocop.yml

Without this rule, rubocop warns on curly braces in hash parameters, even when all the parameters are hashes, hence removing only from the last one decreases code readability.
Example:
https://github.com/ammendonca/manageiq/blob/c063ed1fea40e8486b90fd26dd879fc9572a3caa/spec/services/middleware_topology_service_spec.rb#L72
More info here:
https://github.com/bbatsov/rubocop/issues/2063

Add rubocop rule for curly braces in hash parameter to depend on context

---

i18n.md

Updated the `PostponedTranslation` example to match the changes in ManageIQ/manageiq#9086 .. the non-format-string arguments are no longer passed directly to the constructor, instead, a block is passed, which can be evaluated only when the translation is actually needed.
Cc @mzazrivec

PostponedTranslation - use block for the second argument

---

.rubocop.yml

because https://github.com/bbatsov/rubocop/issues/2280 is closed

allow auto-correct of ExtraSpacing

---

developer_setup.md

- npm:
In Fedora 24, *npm* package is already packed in nodejs:
https://bugzilla.redhat.com/show_bug.cgi?id=1339284#c5
- gcc-c++:
I belive we are not using event-machine Gem anymore
correct me if I'm wrong :blush:

Updated packages in Developer Setup

---

.rubocop.yml

Summary:
---
Just kidding, I actually have been meaning to submit this since the beginning. This is what I'd consider pretty standard Ruby style across most projects.
See https://github.com/bbatsov/ruby-style-guide/blob/master/README.md#spaces-braces
Also see [how to vote for this change](https://github.com/ManageIQ/guides/pull/137#issuecomment-233012107)
No spaces after (, [ or before ], ). Use spaces around { and before }.
```ruby
some( arg ).other
[ 1, 2, 3 ].each{|e| puts e}
some(arg).other
[1, 2, 3].each { |e| puts e }
```
{ and } deserve a bit of clarification, since they are used for block and hash literals, as well as string interpolation.
From the bbatsov styleguide:
For hash literals two styles are considered acceptable. **The first variant is slightly more readable (and …

Removes rule enforcing no space in curly braces

---

.rubocop.yml

...by disabling it.
This commit is a replacement for b912041 which accidentally enabled the *opposite* - enforcing a space. This change allows for BOTH styles to be used without the bot screaming at anyone, as was originally intended.

Fix 'space in hash literals' cop

---

developer_setup.md

the `Curb` gem wants to install a native extension, which requires `libcurl`.
cc @lucasponce

Add libcurl for Fedora, used by curb

---

developer_setup.md

In case ManageIQ is being installed on a fresh OS X chances are that the
developer tools have not been installed. This results in an error about
missing symbols and/or libraries during the installation of Nokogiri gem.
The patch adds a brief explanation in the troubleshooting section
explaining how to install developer tools and try `bin/setup` again.
Signed-off-by: Gregor Berginc <gregor.berginc@xlab.si>

Add a note on missing developer tools in OS X

---

developer_setup.md
developer_setup/postgresql_software_collection.md

This patch adds documentation explaining how to install PostgreSQL 9.4
in CentOS 7 using SoftwareCollections.org.

Install PostgreSQL 9.4 with software collections

---

.rubocop.yml

The bot uses this as the base config for running rubocop on our repos.  In PRs I feel like I frequently see comments about AbcSize and line length.  While some people look at this and make corrections, others completely ignore the comments.  Also, [AbcSize](http://www.rubydoc.info/gems/rubocop/0.37.2/RuboCop/Cop/Metrics/AbcSize) is rarely addressed.
ABC Size > 15 is not hard to do.

Loosen rubocop requirements for less noisy PRs

---

developer_setup.md

This can be used on systems which don't offer PostgreSQL 9.4 from their default repos and as an alternative to SCL
Fixes #140

Add a link to the instructions to install PostgreSQL from the PGDG repos

---

developer_setup/running_test_suites.md

It is not clear why other tasks run :setup before, not test:providers:amazon, is it expected?

Invert order of amazon provider tasks

---

architecture/providers_overview.md

Due new pluggable provider code structure, the link to the Amazon::CloudManager class was broken

Fix broken link

---

README.md
service_ui/skinning.md

taken from ManageIQ/manageiq-ui-self_service#235
This documents skinning for the Service UI.

Add service_ui/skinning - documents skinning in the Service UI

---

developer_setup/postgresql_software_collection.md

This patch fixes a typo in the name of the package used in the instructions to
install PostgreSQL using software collections.
Signed-off-by: Juan Hernandez <juan.hernandez@redhat.com>

Fix typo in PostgreSQL software collections instructions

---

README.md
rest_api.md

This makes more sense when on the website, and if you’re viewing on Github this is one fewer hops and the docs are readable.

Remove rest_api file and link to website.

---

i18n.md

This is about not applying `translate` filter on a dynamic content.

Add more docs on angular-gettext caveats

---

developer_setup.md

This might return a `could not change directory to` error, but that doesn't interfere with the `psql` command.

No postgres user password is required if sudo is available

---

i18n.md

The previous Zanata links for the Service UI and Amazon Provider were
switched. This change corrects the links and changes 'Self-Service' to
'Service' to reflect the repo name change.

Update Zanata project links to correct pages

---

i18n.md

Markdown on GitHub seems to parse differently than parser that is used for ManageIQ.org page, see http://manageiq.org/docs/guides/i18n
There has to be spaces around code blocks
@mzazrivec please review

Improved i18n documentation readability

---

developer_setup/classic_ui_split.md

Previous version would create the `spec/manageiq` symlink pointing to `manageiq-ui-classic/manageiq`. Adding more `../` :)

UI split instructions - fix step 6 - wrong symlink

---

developer_setup/classic_ui_split.md

because otherwise, we get an error trying to find `spec/manageiq-ui-classic`
Cc @Fryguy

UI split - use absolute path for the manageiq-ui-classic :git link

---

developer_setup/classic_ui_split.md

This adds info on how to automatically convert a ManageIQ/manageiq PR to a ManageIQ/manageiq-ui-classic PR. 
This does not preserve comments, labels, assignees, etc. but it *does* preserve the PR description and title, and the commits :).
---
Now also in script form: https://github.com/himdel/dotfiles/blob/master/bin/move-pr

UI split - add PR migration instructions

---

developer_setup/classic_ui_split.md

needed to be able to run `bundle install` in ui-classic, when the `Gemfile` contains `gemspec`.
Fixes ManageIQ/manageiq-ui-classic#42

UI split - add a guard around the gem in Gemfile.dev.rb

---

developer_setup.md
developer_setup/classic_ui_split.md

* change notion to plugin development rather than provider development
* make use of `override_gem` method
I also added tweaked it to clone the plugins in a subdirectory ***inside*** your manageiq checkout.
I know it's controversial and debatable. But I think it reduces the chance of breaking other plugins or the core, because doing `ag -r` or `grep -r` or whatever to grep through your directory will also hit the plugins. (Some commands, like `git grep` will not, but alas)
I tend to make that change also to the `developer_setup/classic_ui_split.md` file.
wdyt @martinpovolny @himdel @Fryguy @bdunne 
https://github.com/ManageIQ/manageiq/pull/13193 would add `plugins/` to `.gitignore`

change docs to plugin development

---

.rubocop_base.yml

There are times that onelining a method is fine.  There are times
when it's not.  Let the developer decide when it's appropriate.
cc @bdunne @Fryguy @chrisarcand 
This PR will hopefully cut down on some of the noise seen in many files:

Empty methods don't have to be onelined.

---

developer_setup/classic_ui_split.md

`echo "override_gem 'manageiq-ui-classic', :path => File.expand_path('../manageiq-ui-classic', __dir__) >> Gemfile.dev.rb`
... was missing a double quote.

Fixes typo on split directions

---

.rubocop_base.yml

We already enable the metrics that we care about via the
.rubocop_cc_base.yml .
@jrafanie Please review

Disable metrics from rubocop.

---

developer_setup.md

The path to "manageiq-content" was incorrect.
/cc @Fryguy

Fixes typo in `override_gem` path

---

coding_style_and_standards.md

The old text referenced a very old fork of the Ruby style guide, however
it is very difficult to keep that up to date.  Instead, I think it's
easier to reference the current Ruby style guide, and then point out the
limited number of changes we enforce through rubocop.
This will also allow me to delete the current fork of the ruby style guide we
have, as I feel it's counterproductive.

Clarify Ruby style guide reference

---

.rubocop_base.yml

Using `//` to delimit regular expressions is something found in most languages and feels much more natural to me than `%r{}`. I believe that people must at least partially agree with me, as I've put slashes in regexs in my code constantly without complaint. Given that this has happened over and over, I don't see a point in continuing to ignore a cop when we can just disable it.
I believe the argument against using slashes is that you then must escape forward slashes in your regex. I think this is a pretty weak point, as you still need to escape other such special characters anyway.
I have turned enforcement of style for regexs off rather than enforcing slashes. Note we can also enforce slashes on single line regexs and %r for multiline if you like. I'm against mixed because although I …

Disable enforcement of %r{} in regex

---

developer_setup.md

Unusually, since the gem uses FFI at runtime, you don't need this lib
for `bundle install` to succeed, but `require 'openscap'` will fail.
Moreover, app/models/openscap_result.rb currently swallows the `require` failure,
resulting in more confusing ``undefined method `oscap_cleanup'`` error:
https://gist.github.com/cben/11af8299c6c85111f5355b6db8c750ce
@moolitayer please review.
- Is `openscap` package enough without `openscap-devel`?  Seems to work.
- This is too easy to miss, I was never aware I need it.
Could we maybe arrange for bundler or bin/setup to fail / give warning
without it?
- I think `with_openscap_arf` should validate `openscap_available?`
returned true, but that's a separate discussion.

Document openscap lib required for openscap gem to work

---

.rubocop_cc_base.yml

We are running 2.3 on appliances and this now allowes Rubocop to
understand features in Ruby 2.3 such as the lonely operator &.

Updated Target Ruby Version to Ruby 2.3

---

developer_setup.md

Followup to #189
Without the lib, manageiq will not crash, but some of the container SSA
functionality will be skipped.
AFAICT it affects:
- collection of `OpenscapResult` (`collect_compliance_data`)
- its parsing into `OpenscapRuleResult`s (`create_rule_results`).
- display of these results.

clarify openscap is only needed for some container SSA functionality

---

developer_setup/classic_ui_split.md

seems like some `ln` implementations resolve relative paths on link creation, while others just create the link, doing the resolve only when accessed.
That makes `ln -s ../../manageiq/ spec/` ambiguous.
Resolving by explicitly cding to `spec` first.
---
Cc @Fryguy , @chessbyte , @isimluk (because you all were active in #188)

UI split - make the ln -s not rely on current path vs target path

---

developer_setup/plugins.md

* added section on remotes
* change remotes to https, because you cannot push to https by default, which makes it safer for people with merge perms on upstream
@Fryguy

Plugin development

---

developer_setup.md

for puma < 3.7.0, we need `libssl1.0-dev`
(presumably, for the newer one, it will be `libssl-dev`)
Relevant issue:
https://github.com/puma/puma/issues/1136
Fixed by:
https://github.com/puma/puma/pull/1178

developer_setup - debian - add libssl1.0-dev needed for puma

---

README.md

It's essential after all the repo splits, and "plugins" wasn't a word I was searching for, this may help more people notice it.

Increase visibility of Plugins guide

---

developer_setup.md

As requested, this adds help for issues installing the `sys-proctable` gem.

Add help for sys-proctable installation issues

---

providers/openshift.md

Also fixes some typos and cleans up the original docs for openshift.
~~Note:  There is currently a [bug with minishift](https://github.com/minishift/minishift/issues/710) when using the described addon.  Eventually, the idea is that this guide can be trimmed down if this addon is included in the core `minishift` project, but for now, a workaround has been included to make this work regardless if that bug is fixed or not.~~
This bug has been isolated [here](https://github.com/minishift/minishift/issues/729), and the current workaround is to just not used string based args with spaces (which I have updated the addon to do).

Adds minishift instructions to the openshift developer guides

---

providers/openshift.md

https://github.com/ManageIQ/manageiq-gems-pending/commit/1911b8ac36f97a66e161009704fbf328e4961dd0 dropped `MiqUUID.get_uuid` causing the steps in this guide to fail.
cc @durandom

MiqUUID.get_guid was dropped in favor of SecureRandom.uuid

---

README.md

@NickLaMuro added some openshift setup instructions (thanks!), which means we should be mentioning openshift in the "provider setup instructions" list in README :).

Add openshift link to "Provider setup instructions"

---

providers/containers.md

As per subject, the markdown syntax for the anchor was wrong.

Fix link to "Smart State Analysis demo"

---

architecture/providers_overview.md

As per subject, use relative links to fix the anchors to Enterprise and Capacity And Utilization pages.

Fix links to Enterprise page

---

README.md
labels.md

Extracted from my talk article:
http://talk.manageiq.org/t/common-labels-across-repos/2285
Might be easier to review via the rendered version: https://github.com/Fryguy/guides/blob/7fdb3e8efb01e4ed25bf92230ca95a232f7c868d/labels.md

Add repo labels and colors documentation

---

.rubocop_base.yml

Enforce using parentheses for methods that have arguments.  I added a bunch of DSL type methods to the exception list.

Enable Style/MethodCallWithArgsParentheses with exceptions

---

developer_setup.md

Installing ManageIQ on Ubuntu 16.04 has failed due to wrong package: libssl-dev.

Ubuntu package fix for bundle install

---

developer_setup/plugins.md

As using `Gemfile.dev.rb` is deprecated this guide change is need.

Updates usage of Gemfile.dev.rb to bundler.d

---

.rubocop_base.yml

When enabled, it will output the following:
```
test.rb:1:7: C: Do not use trailing _s in parallel assignment. Prefer a, b, = 1, 2, 3, 4.
a, b, _, _ = 1, 2, 3, 4
^^^^^
```
Thanks for mentioning this one @carbonin

Improve readability by disabling Style/TrailingUnderscoreVariable

---

developer_setup/minimal_mode.md

MIQ_DISABLE_RRS was removed from the ManageIQ repo in
manageiq/manageiq@5ae313371ba86ec2a4ffdea77a429f87b8429d72
@miq-bot add_label technical_debt
@miq-bot assign @Fryguy

Remove workers that no longer exist and the referrer checking variable

---

developer_setup.md

The libssl1.0-dev is no longer in the apt repositories
```bash
$ sudo apt install libssl1.0-dev gives
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libssl1.0-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'libssl1.0-dev' has no installation candidate
```
When installing libssl-dev, libssl it resolves to libssl1.0.2-dev and works fine.
I hope the explanation is sufficient- if not, please let me know what additional information should I supply

Update developer_setup with correct libssl-dev name from apt

---

developer_setup/running_test_suites.md

Add a mention of `rake environment jasmine`, right now it's not mentioned anywhere in `guides`.
Cc @skateman

test suites - mention JS specs and environment jasmine

---

developer_setup.md

I tried installing miq on a mac in school today, this is the list of things that had to be fixed - should probably be mentioned in the guides.
* With ruby installed as a different user, you can't `bundle install` anything - a workaround is to install the bundle locally
* Nokogiri 1.7.2 bundles it's own version of libxml2 on macs, but fails to compile on a missing LZMA_OK constant
* sys-proctable tries to install an aix version by default and fails

Developer setup - solutions for a bunch of Mac problems

---

developer_setup/plugins.md

Using only relative path without `__dir__` causes issues when gems are
loaded from different place.

Adds note to plugins guide about relative path with override_gem

---

vagrant_developer_vm.md

Just configured using vagrant. Checking `uname` shows it's fedora 25 and in vagrantfile memory should be 6GB
\cc @Fryguy

Some inconsistence with current vagrant scripts

---

.rubocop_base.yml

Disables the [cop that declares the use of double negatives (`!!`) always bad.](http://www.rubydoc.info/gems/rubocop/0.47.1/RuboCop/Cop/Style/DoubleNegation)
Double negatives are useful for forcing values/`nil` to a boolean value as a return value.
Rather than pontificate on why they should be allowed, I'll just point out that this change is basically a formality and I believe shouldn't merit a ton of distracting debate as we already knowingly use and prefer double negatives in our codebase:
* https://github.com/ManageIQ/manageiq/issues/11954
* https://github.com/ManageIQ/manageiq-api/pull/59
* (More I can't find)
cc/ @imtayadeway

Disable DoubleNegation cop

---

developer_setup.md

More accurately specify that the version dependencies are minimums

Don't document installation steps of ruby version managers

---

README.md
developer_setup/debugging.md

adds instructions on setting up remote/interprocess debugging via `pry-remote`

add doc for debugging

---

README.md

Link to the API repo’s contributor’s guide to ensure it is always the most up to date version.

Add link to CONTRIBUTING.md in API Repo

---

ui/forms.md
ui/patterns.md

This adds a document on the current state of forms, conversion routes between the various stages of angular conversion, and a tentative plan for the Angular (2+) future.

ui - add Forms document

---

developer_setup.md

`dnf` is no longer available for CentOS 7 users. Advise users to use `yum` instead.

Add 'use yum' advice notice for CentOS users

---

architecture/source_code_layout.md

Remove the gems and spec/automation folders which are not part of this
repository anymore.
Need to add plugins folder, in a separate pr.

Remove deprecated parts from Source Code Layout

---

developer_setup.md

At least on mac, I have found that avoiding `sudo npm install -g` is helpful in preventing odd permissions issues that can come up.  It is possible to keep npm entirely in userspace, so I added a note to the guide about that and removed sudo from the example commands.

Advise to try npm install without sudo first

---

.rubocop_base.yml

Get back to our previous defaults
Based on https://github.com/bbatsov/rubocop/blob/master/config/default.yml#L1224-L1234

Override the default overrides

---

labels.md

GitHub changed how they rendered some of the old colors such that they
show black text on the background which was hard to read.  These new
colors put it back to being legible.
Before
After
@chessbyte Please review.
See also https://github.com/ManageIQ/manageiq-release/pull/57

Update label colors due to GitHub change

---

.rubocop_base.yml

Running rubocop locally on a ManageIQ plugin will check the
spec/manageiq and vendor paths unless explicitly ignored, resulting in
1000s of lines of unnecessary output.

Ignore manageiq fixture path and vendor path

---

providers/openshift.md

Followups from https://github.com/ManageIQ/manageiq-providers-openshift/pull/75

Openshift VCR-recording script, touch up minishift instructions.

---

.rubocop_base.yml

with the upgrade of rubocop, it changed to the new `annotate` default, causing a lot of warnings like..
```
Style/FormatStringToken - Prefer annotated tokens (like %<foo>s) over template tokens (like %{foo}).
```
(example: https://github.com/ManageIQ/manageiq-ui-classic/pull/3378#issuecomment-363461332)
[docs](http://www.rubydoc.info/gems/rubocop/0.52.0/RuboCop/Cop/Style/FormatStringToken)

Rubocop base - set Style/FormatStringToken back to template

---

i18n.md

Fixes a syntax issue in one of the N_ examples.

Clarify the N_ new syntax example

---

providers/dev-guide.md

Updated link to the `db/migrate` folder in providers dev guide. Switched repo from `manageiq` to `manageiq-schema`.

Fix broken migrations link

---

README.md
ui/register_react_component.md

Shared component API guide to show how to create and use and simple list of interaction with such component.

Add information about shared component API

---

developer_setup/running_test_suites.md

Instructions in the document were a bit out-of-sync with the actual
state of affairs and this commit attempts to fix this.
There are two major things that we did in order to get documentation
back up to speed. First, we removed the parts of the documentation
that were no longer true and added some generic documentation on how
to run tests in vast majority of ManageIQ repos.
To finish off the sync operation, we expanded the section about the UI
tests that behave quite differently from the rest of the bunch.
/cc @gberginc @matejart

Update document on running test suites

---

providers/dev-guide.md
providers/persister/inventory_collections.md

**Issue** https://github.com/ManageIQ/manageiq/issues/17396
Description of ```ManagerRefresh::Inventory::Persister#add_collection()``` and builder classes for definition of InventoryCollection
Cc @agrare

InventoryCollection definition 

---

providers/persister/inventory_collections.md

InventoryCollection definition changes `:builder_params` to `:default_values`
Based on https://github.com/ManageIQ/manageiq/pull/17742
cc @Ladas, @martinpovolny

InventoryCollection changed builder_params => default_values

---

developer_setup.md

Since https://github.com/ManageIQ/manageiq-ui-classic/pull/3776, we're depending on node 8 or newer.
Talk article: http://talk.manageiq.org/t/changed-minimal-node-js-version/3695
PR changing the UI dependency https://github.com/ManageIQ/manageiq-ui-classic/pull/4429
Cc @Fryguy

developer setup - link to actual required node version, do not hardcode 6

---

providers/redfish.md

Instructions courtesy of @tadeboro (from https://github.com/ManageIQ/manageiq-ui-classic/pull/3912), thanks!
These are just instructions on setting up a mock version of yet another provider - https://github.com/ManageIQ/manageiq-providers-redfish

Redfish - add mock provider setup instructions

---

README.md
ui/plugins.md

Cc @martinpovolny 
Thanks to the whole v2v effort, we now support UI plugins. But looks like they are not documented at all yet :).
We should fix this, but for now, I mostly needed a place to write down the list of libraries the plugin can always expect to be available. Hence this PR.
(We'll probably need to add a few more, like react & react-dom.)

Start of the UI plugin guide

---

.rubocop_base.yml

Ignore migration methods (references and index) for the rubocop MethodCallWithArgsParentheses cop.
Ref: https://github.com/ManageIQ/manageiq-schema/pull/242#issuecomment-412886651

Ignore references & index methods for parentheses

---

.rubocop_base.yml

Parentheses shouldn't be required around add_reference, see https://github.com/ManageIQ/manageiq-schema/pull/258#issuecomment-415752604
Follow up to https://github.com/ManageIQ/guides/pull/326

Don't require parens around add_reference

---

.rubocop_base.yml

`warn` is similar to `puts`, so treat them the same in `rubocop`'s eyes and have it not require parenthesis.

No parens required for warn

---

ui/react_forms.md

GH flavoured markdown needs an empty line before the table unlike e.g. the VS Code editor.
Ping @Hyperkid123, @himdel

Fix table formatting for ReactForms.

---

developer_setup.md

The console looks up ip addresses. This uses the `ip` command.
While it is not available on native macs, homebrew does have a wrapper.
```
1) ManageIQ::ApplianceConsole::Cli#set_replication should configure repmgrd when auto-failover flag is set
Failure/Error: self.primary_host      = LinuxAdmin::NetworkInterface.new(NETWORK_INTERFACE).address
AwesomeSpawn::NoSuchFileError:
No such file or directory - addr
```
After this install, tests pass in the appliance console.
Thank you open source.

add iproute2mac tool for appliance_console devs

---

.rubocop_base.yml

Add `#remove_reference` to the list of rubocop exclusions for the `Style/MethodCallWithArgsParentheses` cop.
Ref: https://github.com/ManageIQ/topological_inventory-core/pull/104

Add remove_reference to the rubocop exclusions

---

.rubocop_base.yml

This change allows the use of either style of word arrays:
```ruby
["foo", "bar", "baz"] # both valid
%w[foo bar baz]
```
And symbol arrays:
```ruby
[:foo, :bar, :baz]    # both valid
%i[foo bar baz]
```
The style of symbol/word arrays will still be enforced, but will change in the future to match the defaults from `rubocop`.  Currently `%i()` and `%w()`, but will change to `%i[]` and `%w[]` in a future PR.

Disable Style/SymbolArray and Style/WordArray

---

developer_setup.md

Fixes an error while running `bin/update`.
Under the covers it was failing from task `rake update:ui`
```
ERROR in ./node_modules/spin.js/spin.css (
./node_modules/css-loader??ref--8-1!
./node_modules/postcss-loader/lib??ref--8-2!
./node_modules/resolve-url-loader!
./node_modules/sass-loader/lib/loader.js??ref--8-4!
./node_modules/spin.js/spin.css)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: Node Sass does not yet support your current environment:
OS X 64-bit with Unsupported runtime (67)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.4
```
Apparently odd numbers for node are unstable, so I needed to downgrade from v9 to v8
/cc @himdel

Guide for installing a stable node on mac

---

ui/provider_plugin.md

There is no code in `app/javascript/packs/provider-dialogs-common.js` that would look at `buttonData.button`.
This was either an artefact of development, or originally used for extra props, removing to prevent confusion.
Cc @martinpovolny

provider_plugin - drop :button from example

---

developer_setup.md

Bower is not used for branches newer than Gaprindashvili

Remove bower from developer setup manual

---

.rubocop_base.yml

Update rules to work with Rubocop 0.69.0.
Replacement for 
https://github.com/ManageIQ/guides/pull/343

Update rules to work with Rubocop 0.69.

---

.rubocop_base.yml

Starting in version 0.68 the performance cops were split out into their own gem called `rubocop-performance`. It has to be explicitly required or we'll start getting these:
`Warning: unrecognized cop Performance/Casecmp found in .rubocop.yml`

Add explicit require for rubocop-performance

---

.rubocop_base.yml

As of rubocop 0.5.3, they added the rule `Naming/RescuedExceptionsVariableName`. This checks the variable name assigned to exceptions when you do something like this:
`rescue StandardError => err # <== I'm talking about 'err' here`
It's a nice idea in theory. Unfortunately, they chose a default preferred value of "e", which means that any other variable name will generate a rubocop warning about the exception name.
I think violates the whole "meaningful variable names" concept. I think "err" hits the sweet spot between meaningful and concise, so I'm suggesting this tweak.
Edit: in fact, it violates their *own* default variable naming enforcement for the also-new `Naming/UncommunicativeMethodParamName` option, which defaults to a minimum of 3 characters.
If you said "either/or" I'll count …

Change default preferred exception name to 'err'

---

developer_setup.md
developer_setup/git_workflow.md
writing_guides.md

During my review of the developer setup steps, I took a lot of notes and rewrote the developer guide to reflect the current state of required software and dependencies.
* Many caveats that had been written into the guide over time are no longer applicable, so I dropped them.
* I restructured the order in which the set up steps occur. Hopefully the steps are clear to follow, especially for new contributors.
* I  combined the steps as much as possible, deviating to platform-specific sections only where necessary.
* I dropped the troubleshooting section. I encountered some of them during my review and incorporated the fixes into earlier steps. Others were no longer applicable.
* I factored the `git` and GitHub steps into a separate guide.
I reviewed these steps on Fedora 30 and macOS 10.14, …

Rewrite developer guide

---

README.md
remote_consoles.md

Follow-up on https://github.com/ManageIQ/manageiq/pull/19049 as discussed with @jrafanie.

Add development guide for remote consoles

---

reviewers_guidelines.md

- Changes "technical dept [_sic_]" reference to "technical debt"
- Changes "continously [_sic_]" to "continuously"

Fixes typos in `reviewers_guidelines.md`

---

developer_setup/plugins.md

This will fix the broken link reported in https://github.com/ManageIQ/guides/issues/377.
cc:  @gmcculloug

Fix incorrect URL in plugins guide

---

.rubocop_base.yml

These methods are  usually treated as a DSL and should be ignored
by Style/MethodCallWithArgsParentheses.
See comments in https://github.com/ManageIQ/manageiq-automation_engine/pull/369#discussion_r324851649
for more details.

Add methods to be ignored by rubocop

---

.rubocop_base.yml

Proposing to disable the [Rails/HttpStatus](https://rubydoc.info/gems/rubocop/0.69.0/RuboCop/Cop/Rails/HttpStatus) cop
The current setting for the cop is to prefer symbols, which means:
```
render :foo, status: 200
render json: { foo: 'bar' }, status: 200
render plain: 'foo/bar', status: 304
redirect_to root_url, status: 301
render :foo, status: :ok
render json: { foo: 'bar' }, status: :ok
render plain: 'foo/bar', status: :not_modified
redirect_to root_url, status: :moved_permanently
```
I consider the numeric codes more readable and clearer,
but would not go as far as forcing people to use them.
(Translation table between actual status codes and rails symbols: https://guides.rubyonrails.org/layouts_and_rendering.html#the-status-option)
=> just disabling the cop in this PR
Please vote on …

Rails/HttpStatus - disable cop

---

.rubocop_base.yml

Parameters like 'vm' and 'dc' are quite meaningful and often used in
providers so I propose to make an exception to the rule of minimum three
characters length for those.

Some parameter names are short but meaningful

---

.rubocop_base.yml

Don't suggest `i.positive?`
Allow `i > 0`
Alternative would be to push using numeric comparison:
```yaml
Style/NumericPredicate:
AutoCorrect: false
EnforcedStyle: comparison
```
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NumericPredicate
Please guide me if I did this wrong (this is my first run in with the cops)
EDIT by @Fryguy: Please vote with
- :+1: if you want to enforce `comparison` (`i > 0` only)
- :-1: if you want to keep it the way it is, and enforce `predicate` (`i.positive?` only)
- :rocket: if you want it `disabled` (both are allowed)

Encourage regular numeric comparisons

---

developer_setup.md

thanks @mturley 
developers should now be using Ruby 2.5.x
Fixes https://github.com/ManageIQ/guides/issues/371

Update ruby version to 2.5

---

.rubocop_base.yml

As a reviewer, I'd prefer to re-enable this cop for a couple of reasons:
- With it disabled, it is harder to differentiate between a hash and an inline block
- With the cop disabled, it doesn't complain about inconsistencies in leading and trailing spaces like `{:a => 1 }` or `{ :a => 1}`
This change only affects hashes, not in-line blocks and enforces no leading or trailing spaces inside the braces.
Please vote :+1: if you approve of the change or :-1: if you prefer to leave it disabled.  I think there was a lot of unrelated discussion about Arrays, Blocks and String interpolation (which are not controlled by this cop) in #137 which led to confusion.

Revert #137 and enforce no spaces inside hash braces

---

.rubocop_base.yml

Most of the code base is already in implicit mode, but rubocop changed
their default to explicit.  This moves it back for consistency as well
as my personal preference :)
https://www.rubydoc.info/gems/rubocop/0.52.1/RuboCop/Cop/Style/RescueStandardError
Please vote on what you prefer with 👍  or 👎  on this comment  (:+1: means you want implicit like this PR; :-1: means you want explicit as per the rubocop default)

Set Style/RescueStandardError to implicit

---

ui/remote_consoles.md

Comes from a gitter discussion :point_up: [January 15, 2020 5:18 PM](https://gitter.im/ManageIQ/manageiq?at=5e1f497c51fcd0256c92df11),
webmks consoles won't work without the webmks implementation from a vmware sdk, with unclear (or nonexistent?) license, which we can't distribute. But that bit doesn't seem to be documented :).
(I think the current link is https://www.vmware.com/support/developer/html-console/, but not sure whether to have such a link in the documentation.)
(also relevant https://github.com/ManageIQ/manageiq-ui-classic/pull/5044)
Cc @martinpovolny , @skateman

Remote consoles - add steps to enable WebMKS

---

ui/provider_plugin.md

The form referenced as an example for provider plugin toolbar forms was deleted in https://github.com/ManageIQ/react-ui-components/pull/170 beacuse it was never used.
Changing the link to a real, used example from manageiq-providers-lenovo.
Fixes #402

Link different example form for provider plugin toolbars

---

developer_setup.md

`gulp-cli` was needed globally to build SUI, dropped in ManageIQ/manageiq-ui-service#719.
`webpack` was needed globally before the advent of `webpack-cli`, +- https://github.com/ManageIQ/manageiq-ui-classic/pull/3776.
`yarn` can still be installed via `npm install -g yarn`, but it's not *the* recommended way of doing that, adding a link to https://classic.yarnpkg.com/en/docs/install/.
Also a slight rewording to *not* sound like we need node 10.16 exactly, node 12 is supported since ManageIQ/manageiq-ui-classic#6008 (and node 14 *should* work with master too).

developer_setup: remove gulp-cli and global webpack, add yarn install link

---

providers/openshift.md

Add instructions for using CodeReady Containers as a local OpenShift 4 provider.
Support for OpenShift 4/CRC was added in https://github.com/ManageIQ/manageiq-providers-openshift/pull/164

Add instructions for adding CodeReady Containers

---

plugins/generator.md

The provider generator now takes a --manager-type= argument allowing for manager types other than clouds to be created.
Updates after https://github.com/ManageIQ/manageiq/pull/20352/

Updates to the provider generator documentation

---

i18n.md

As an example, [this](https://github.com/ManageIQ/manageiq/blob/master/.tx/config#L6) is the message catalog in the [manageiq](https://github.com/ManageIQ/manageiq) repo.

`tx push --source` uses the `.tx/config` file to determine the message catalog file name

---

.rubocop_base.yml

This can be super annoying when doing anything in the API :exploding_head:

Stop RuboCop complaining about `id` as an uncommunicative argument

---

developer_setup.md

After the `pg_createcluster` command the database isn't automatically started so without also running `pg_ctlcluster 10 main start` it cannot be connected to.
```
Success. You can now start the database server using:
pg_ctlcluster 13 main start
Ver Cluster Port Status Owner    Data directory              Log file
13  main    5432 down   postgres /var/lib/postgresql/13/main C
```

After pg_createcluster postgres isn't running

---

providers/writing_a_new_provider.md

Add a guide for writing a new provider from scratch

---

developer_setup.md

Originally this assumes the user already has an SSH key setup and does not emphasize that we use forks for our development. This is a slight rephrasing and reordering of existing content.

Moved Git Workflow link up for clearer steps

---

providers/targeted_refresh.md

After https://github.com/ManageIQ/manageiq/pull/21225 the core persister defaults to the proper strategy for full/targeted refreshes automatically without the provider author having to specify it.

Specifying a targeted strategy no longer required

---

providers/writing_vcr_specs.md

Follow-ups:
* Add spec test examples for existing targeted refresh guide
* Examples for auto-generating inventory with a rake task

Add a guide for writing provider VCR specs

---

.github/workflows/ci.yaml

There is an issue in CI with building libv8 that has been fixed in a
newer rubygems.  Instead of just upgrading Ruby gems, we might as well
update Ruby itself.
See also ManageIQ/manageiq.org#1092

Upgrade build to Ruby 2.7

---

i18n.md

Updated translation documentation to correct javascript plural translation from `n_` to `n__`.

Updated translation documentation

---

providers/writing_a_new_provider.md

This adds the optional `--js` parameter to the provider generator command added by https://github.com/ManageIQ/manageiq/pull/21954
In the future a new guide on adding a provider specific button or form would be great as well.l

Update "writing_a_new_provider" with the new JS option

---

triage_process.md

After the merge of #502 , the actual usage of the links was left out.  This PR fixes that.
@bdunne Please review.

Fix invalid links on triage page

---

providers/events.md

The `self.class.parent` method was deprecated in rails 6.0 and removed in 6.1

Fix events doc calling `Module#parent`

---

providers/adding_a_new_model.md

During some enhancements we tried to add to the autosde provider, we encountered difficulties in finding the correct way to 
add a model collected from the provider-client to miq inventory (the collect-parse-build-persist flow).
After figuring it out, we've written a short guide for this, and @agrare suggested that we add it to manageiq/guides.
We've found this article about the inventory, which seems like a good place to add examples that might make it easier for future developers. We use `storage_manager` as the provider class in these examples.

Guide for Adding a New Model

---

developer_setup.md

Running into issues setting up a new dev env from zero (on Mac M1). @Fryguy gave me the supported version range for NodeJS.
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>

Updating max versions for Node and PostgreSQL

---

developer_setup.md

We currently do not specify the locale when creating our pod or appliance database So lets not set the locale for our development database.
Most mac developers use the default mac install, which takes the locale from the environment (`en_US`) and doesn't pass it in.

Do not specify the locale when creating a database

---

developer_setup.md

Here is a first stab of kafka installation instructions for developers.
---
Kafka currently supports java versions 8, 11, 17, but has deprecated jdk 8. I include version 19 since that is the version that the mac installs by default.
- Only really tested on the mac.
- Not totally sure if the system wide java command is necessary on the mac.
/cc @nasark @agrare

Instructions on installing kafka

---

external_auth/ipa-configuration.md

When we moved to using a manageiq user, we need to add this user so it has permission in sssd.conf.
See also:
https://github.com/ManageIQ/manageiq/pull/22715
https://github.com/ManageIQ/httpd_configmap_generator/pull/77
https://github.com/ManageIQ/manageiq-documentation/pull/1743
https://github.com/ManageIQ/manageiq-appliance_console/pull/220

Add manageiq user to allowed_uids for sssd

---

developer_setup.md

- Kraft is optional
- should also start zookeeper services if using brew and not kraft
@miq-bot add_labels enhancement, quinteros/yes?
@miq-bot add_reviewer @agrare

Fix zookeeper/kraft developer setup

---

developer_setup.md

- Move Kafka into the services section
- Cleanup and consistency with other service sections
- Add Kafka to requirements table
@nasark Please review.

Move Kafka into the services section + cleanup

---

providers/writing_a_new_provider.md

We now have better support in core for `Regions` that use a `config/regions.yml` file, update the writing_a_new_provider to use this.

Update writing_a_new_provider to use config/regions.yml

---

developer_setup.md

Add developer ovirt-engine-sdk instructions for C compiler errors

---

providers/openshift.md

The instructions here are out of date and fail when followed using a current openshift cluster, specifically 
`ClusterRole` has been moved out of the root apiGroup and into `rbac.authorization.k8s.io/v1`, also an `apiGroups` property is required in `ClusterRole.rules` now
* Drop minishift instructions since we do not support openshift v3 any longer
* ~~TODO update CRC instructions to fix issues with current versions~~
* Point to the official openshift documentation as it is kept up-to-date on how to create cluster-roles / service-accounts

Update openshift developer setup guide

---

developer_setup.md

Fix issue with bundle config and escaping the config

---

developer_setup.md

The appliance console uses `ip` (via linux admin) to perform many of the functions.

Document ip util for mac appliance_console

---

coding_style_and_standards.md

- Fix bad links or remove them
- Drop Bugzilla references and refer to external ticketing systems more generically
- Add a case about @-mentions in commit messages

Cleanup some issues with the coding standards

---

developer_setup.md

Fix errors installing the rdkfaka gem while compiling the librdkafka library due to missing openssl/engine.h header file.
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory: /home/agrare/.gem/ruby/3.1.4/gems/rdkafka-0.19.0/ext
/home/agrare/.rubies/ruby-3.1.4/bin/ruby -I/home/agrare/.rubies/ruby-3.1.4/lib/ruby/3.1.0 -rrubygems
/home/agrare/.gem/ruby/3.1.4/gems/rake-13.2.1/exe/rake
RUBYARCHDIR\=/home/agrare/.gem/ruby/3.1.4/extensions/x86_64-linux/3.1.0-static/rdkafka-0.19.0
RUBYLIBDIR\=/home/agrare/.gem/ruby/3.1.4/extensions/x86_64-linux/3.1.0-static/rdkafka-0.19.0
Extracting librdkafka_2.5.3.tar.gz into tmp/x86_64-redhat-linux/ports/librdkafka/2.5.3... OK
Running git apply with /home/agrare/.gem/ruby/3.1.4/gems/rdkafka-0.19.0/dist/patches/rdkafka_sticky …
```

Add instructions for Fedora 41+ openssl-devel-engine

---

external_auth/ipa.md

NTP settings in the UI no longer exists, which is why that section removes it.

Fix minor issues with IPA docs

---

developer_setup.md

`bin/update` command fails when Ansible is not installed locally. This PR updates the developer guides to include instructions for installing Ansible using Homebrew.
Error looks like -
`== ManageIQ:: Providers::Nuage:: Engine ==
bin/rails aborted!
AwesomeSpawn: :NoSuchFileError: No such file or directory - ansible-galaxy`
`Caused by:
Errno:: ENOENT: No such file or directory - ansible-galaxy`
`== Command ["bin/rails db:seed"] failed`
@miq-bot add-label documentation
Please review @Fryguy

Update brew command to install Ansible

---

external_auth/oidc-httpd-configs/authentication.conf

Removed extra % symbol in authentication.conf

Fixing typo in oidc authentication.conf
