architecture/providers_database_architecture.md, architecture/providers_database_architecture/metric.md
Adding Metric model documentation, so far only usage of OpenstackInfra
provider
=> Add Metric model documentation

.rubocop.yml
=> Change severity of certain cops to be lower.

README.md, miq-dev-appliance-setup/MAC/README.md, miq-dev-appliance-setup/MAC/downgrade-vmware-tools.md, miq-dev-appliance-setup/MAC/on_appliance/defines.sh, miq-dev-appliance-setup/MAC/on_appliance/map-source.sh, miq-dev-appliance-setup/MAC/on_appliance/miq-setup.sh, miq-dev-appliance-setup/MAC/on_appliance/run-all.sh, miq-dev-appliance-setup/MAC/on_appliance/software-install.sh, miq-dev-appliance-setup/MAC/on_appliance/source-updated.sh, miq-dev-appliance-setup/MAC/on_appliance/vmware-tools-install.sh, miq-dev-appliance-setup/MAC/setup.md, miq-dev-appliance-setup/README.md
Initial commit of development appliance setup guides and scripts.
=> Development appliance setup guide.

developer_setup.md
Followup to #56 
cc @brandondunne @Fryguy
=> Membership can only be checked if you're in the organization.

developer_setup.md
=> Clean up development setup doc.

miq-dev-appliance-setup/MAC/on_appliance/miq-setup.sh, miq-dev-appliance-setup/MAC/on_appliance/source-updated.sh
Updated scripts to use evm:compile_assets instead of rake assets:precompile.
=> Use rake evm:compile_assets.

developer_setup.md
* fedora's package manager has changed from yum -> dnf
* nokogiri requires that the patch package be installed separately
=> Add Fedora 22 setup.

.rubocop.yml
Extra log filename: https://github.com/ManageIQ/manageiq/pull/1679
Stop insisting on if/unless modifiers: https://github.com/ManageIQ/manageiq/pull/3377
=> Sync rubocop config with main repo

.rubocop.yml
Gems and other libraries shouldn't use them
=> Don't allow GlobalVars by default.

README.md
Deleted the wiki page in #79 but missed a link to it from the README
cc @kbrock
=> Deleted the wiki page in #79 but missed a link to it from the README

architecture.md, architecture/providers_overview.md
General documentation about ManageIQ providers and the various workers associated with providers.
=> Provider overview documentation

developer_setup.md
- Alternative for RVM: rbenv
- Required Ruby version
- Default login and password
=> Additional informations to the developer setup

README.md, developer_setup.md, developer_setup/minimal_mode.md
Explains to developers how to setup and run in minimal mode with selected
workers.
=> Add docmentation for running in minimal mode

developer_setup.md
Instructions to get things up and running on CentOS 7.
=> Add CentOS 7 instructions

developer_setup.md
I noticed in https://github.com/ManageIQ/guides/pull/90 that we're currently listing manual steps for which we have helpful automation.
Helpful automation is helpful.
Fixes #91.
=> Recommend the new bin/setup script

developer_setup.md
- dnf works in Fedora 20+
- Deduplicate setup for extremely similar platforms
=> Update Fedora Dev setup, deduplicate with CentOS setup

developer_setup/minimal_mode.md
Allows for direct URL browsing
=> Note new MIQ_DISABLE_RRS option

developer_setup/running_test_suites.md
Since the SSUI is in a new repo, the tests there are more obvious,
and also no longer follow the pattern in the document.
@chrisarcand Please review.
=> Remove SSUI test instructions

i18n.md
https://manageiq.org/documentation/development/i18n/
=> Corrected markdown for i18n guidelines

developer_setup.md
rugged was added in: https://github.com/ManageIQ/manageiq/pull/3807
=> Add cmake for fedora/centos as a dependency of rugged.

developer_setup.md
Fixes https://github.com/ManageIQ/manageiq.org/issues/239
=> Add bundler help

developer_setup.md
Mention installing of Node + bower for OS/X
=> Add installing of node+bower to OSX section

external_auth/configuration.md
Related PRs:
https://github.com/ManageIQ/manageiq/pull/7470
https://github.com/ManageIQ/manageiq-appliance-build/pull/114
https://github.com/ManageIQ/manageiq_docs/pull/20
https://github.com/ManageIQ/manageiq-appliance/pull/62
=> Renamed cfme in configuration files to manageiq

developer_setup.md
cc @karelhala @mtho11 @ammendonca 
@blomquisg please review
=> remove confusing instruction to run rails s after evm:start

developer_setup.md
Added 9.4+ requirement for PostgreSQL in developer_setup doc.
@Fryguy
=> Add minimum required postgres version

developer_setup.md
Pluggable providers development setup
=> Pluggable providers development setup

developer_setup.md
Added minor fix to dnf install command
=> Updated developer_setup.md

developer_setup/running_test_suites.md
Some extra help to point people at dealing with parallel_tests. Includes some little tips we've picked up since first presenting about this at the ManageIQ summit.
cc/ @jrafanie
=> Parallel tests docs

i18n.md
* new rake tasks
* new projects
* rails engines / plugins howto
=> Update i18n documentation:

architecture/providers_overview.md
File is named "containers" (plural)
=> Fix broken link

architecture/capacity_and_utilization_collection_explanation.md
New website wants a title at the top of the page.
=> Add a title for Cap&U page

i18n.md
Now we just have to run one rake task to update the catalog (rather than four tasks that we did in
the past).
=> Update i18n for latest changes in the process

architecture/providers_overview.md
=> Correct the link to container manager in provider overview page

i18n.md
Fixes rendering on website and improves the sentence a bit.
Resolves https://github.com/ManageIQ/manageiq.org/issues/388
=> Fix i18n page rendering

i18n.md
The filter was implemented in
https://github.com/ManageIQ/manageiq-ui-self_service/pull/185
=> Add documentation for angular substitute filter

README.md, vagrant_developer_vm.md
Adding information about how to use the new Vagrant development image so developers can use it.
=> Added Vagrant info to the developer guide

README.md, developer_setup/classic_ui_split.md
Adding the first version of ui split instructions.
Cc @Fryguy, @martinpovolny
=> UI split instructions

vagrant_developer_vm.md
Added one missing 'rake' command for vagrant steps.
=> Add missing rake for vagrant instructions

providers/hawkular.md
As I promised @martinpovolny in https://github.com/ManageIQ/manageiq-ui-classic/pull/361 here is guide on how to run hawkinit with and without answers file.
@Jiri-Kremser, @pilhuhn, @theute what do you think?
=> Add hawkular's provider to guides

README.md
..adding only the providers which do contain some instructions for developers.
Ping @martinpovolny ;)
=> Link provider setup instructions from README

ui/angular_components.md, ui/patterns.md
Add basic rules to create an Angular components. Description of existing component.
@himdel please check that content is alright.
@miq-bot add_label enhancement
=> Add guidelines for Angular components

developer_setup.md
@himdel, could you check, if it's correct?
(original source: https://gist.github.com/romanblanco/00df8d0feddb0a7c1b2a8db88d45f61a)
=> Added Developer setup guide for Ubuntu / Debian

providers/containers.md
CC @kbrock @NickLaMuro @enoodle
=> containers.md: Add openshift installation link

ui/gtl.md, ui/textual_summary.md
=> Update Textual Summaries and GTLs

ui/button_actions.md, ui/patterns.md, ui/rbac_features.md, ui/toolbars.md
=> UI Guides updates.

ui/textual_summary.md
=> Fix a typo.

architecture/enterprise.md
As per subject, fragments' ids were wrong.
=> Fix links to Enterprise's fragments

providers/openshift.md
As per subject, there was a typo in the Markdown syntax
=> Fix link to minishift

i18n.md
As per subject, the markdown syntax was wrong.
=> Fix link to Zanata

README.md
The file has been renamed in bcc1209c.
=> Fix hyperlink to Hawkular

developer_setup.md
I think that this was missing.
=> Adds yarn install instructions for Fedora / CentOS

developer_setup.md
Adds links to official way of installing of yarn for Linux distros.
Adds yarn to list of installed packages by brew for MacOS.
Adds bash language to few code markups.
Discussed in #230 .
=> Updates yarn installation instructions

developer_setup.md, developer_setup/foreman.md
https://github.com/ManageIQ/manageiq/pull/15669 adds an example Procfile to ManageIQ.
This PR describes some of the moving parts.
=> Add documentation around how to start ManageIQ using Foreman

.rubocop_base.yml
Rather than setting it on every repo, let's maintain the minimum ruby version here
=> Set TargetRubyVersion globally

reviewers_guidelines.md
Updating guides after https://github.com/ManageIQ/manageiq-ui-classic/pull/1636
=> Updated guides with method for fetching a single item with RBAC

developer_setup.md
Added instructions to use the experimental apt repo in debian,
Mention brew upgrade & link for macs,
And mention using nvm as an alternative.
=> Developer setup - need node 6+ now

coding_style_and_standards.md
This is mostly from Yuri and part of them from searching. It's tested during my daily practice.
=> Add git how to part and delete it in TODO

vagrant_developer_vm.md
This is trivial path error and easy to find, but a correct guide looks better.
\cc @Fryguy
=> A small error in manageiq path

coding_style_and_standards.md
@chrisarcand this is docs for docs
=> add docs section

developer_setup.md
This PR adds a line about installing developer tools on OSX and also adds a section for upgrading mac versions.
=> Adds section for upgrading osx

.rubocop_base.yml
It's not something we care about right now.
=> Disable frozen string literal comments

developer_setup.md
=> Update postgres requirement

developer_setup.md
**Description**
While setting up my environment, I encountered an error building the noi4r gem. To fix this, I needed to install this package group.
=> Add missing dependencies to developer_setup for the noi4r gem

ui/angular_components.md
=> Minor style fixes to angular_components.md.

i18n.md
- added missing bracket
- making link clickable
=> Update i18n documentation

reviewers_guidelines.md
@panspagetka please take a look if the description makes sense. Thanks
Links: https://github.com/ManageIQ/manageiq-ui-classic/pull/3131
=> Double checking loaded records

.rubocop_base.yml
=> Disable rubocop Layout/PercentLiteralDelimiters to allow %()

.rubocop_base.yml
- Re-enable the cop with () as the default
=> PercentLiteralDelimiters is Style, not Layout

developer_setup.md
This way it would be more clear to user that only one version manager suffice
=> Edit developer_setup.md

ui/patterns.md, ui/redux.md
We were lacking definition of simple reducers created for our redux. There are two examples of simple reducers and how to dispatch new action.
=> Add reducers example and how to dispatch action for redux

.rubocop_base.yml
Based on https://github.com/ManageIQ/manageiq-appliance/pull/188#issuecomment-384318895
cc @carbonin
=> Add `gem` to the exclusion list

README.md, ui/report_data_api.md
New section about report data API is added, which describes each action and examples of how to use these actions.
=> Add information about report data API

ui/quadicons.md
@miq-bot add_reviewer @martinpovolny 
@miq-bot add_reviewer @epwinchell
@miq-bot add_reviewer @romanblanco 
@miq-bot add_reviewer @himdel
=> Updated quadicon documentation to be consistent with the decorators

ui/patterns.md, ui/provider_plugin.md
Initial words and examples on provider UI plugins.
=> Initial words on provider UI plugins.

ui/patterns.md, ui/react_forms.md
Documentation on how to write React forms inside MIQ
=> Added initial React forms documentation.

developer_setup.md, developer_setup/postgresql_software_collection.md
Removing postgresql 9.4 references and replacing with 9.5.
=> PostgreSQL 9.4 is no longer supported, replace with 9.5

ui/plugins.md, ui/provider_plugin.md
=> Small fixes

.rubocop_base.yml
As requested https://github.com/ManageIQ/manageiq-schema/pull/327#issuecomment-468056092
=> Add trigger dsl methods to rubocop ignore list for method call rule

architecture/source_code_layout.md
FactoryGirl no longer exists. Long live FactoryBot!
=> Upgrade from FactoryGirl to FactoryBot

providers/openshift.md
With the current implementation of this code, the indenting is incorrect, and causes the generated html markup to generate a new list element for each new list item.
The adding of the whitespace in this commit fixes the issue, and allows the markdown processor to properly create a single list.
Link on prod:  http://manageiq.org/docs/guides/providers/openshift
Screenshots
-----------
Notice the change in indent, and the now incremented numbered list:
(for what it is worth, not sure why the highlighting is now working...)
=> [openshift.md] Fix list formatting

ui/patterns.md
Add a link to breadcrumbs documentation that @rvsia is working on.
=> Add a link to breadcrumbs documentation

git_utils/README.md
Changed readme for single repo/multirepo scripts
@martinpovolny please one more merge :)
=> Fix git-utils readme

README.md, automate_url_open.md
preview the new article here: https://github.com/martinpovolny/guides/blob/automate_url_opener/automate_url_open.md
=> Add docs for opening an URL via automate.

ui/dialog_editor.md, ui/patterns.md
moving Dialog Editor documentation from https://github.com/ManageIQ/manageiq-ui-classic/wiki/Dialog-Editor to the guides repo
=> Dialog Editor documentation

ui/breadcrumbs.md
- port from WIKI https://github.com/ManageIQ/manageiq-ui-classic/wiki/Breadcrumbs
@martinpovolny
=> Add documentation for breadcrumbs

ui/quadicons.md
Updating the quadicon specs to be in sync with the changes.
Depends on: https://github.com/ManageIQ/manageiq-decorators/pull/25
Parent issue: https://github.com/ManageIQ/manageiq-design/issues/43
@miq-bot assign @martinpovolny 
@miq-bot add_label pending core
=> Update the docs about quadicons to be in sync with the cleanups

ui/quadicons.md, ui/textual_summary.md, ui/toolbars.md
Add references to react-ui-components.
=> Add references to react-ui-components.

ui/dialog_editor.md
there's no 🍖 in this, just a couple grammar nits
=> Fix minor style and typo things

developer_setup.md
Otherwise you'll have difficulty installing packages for installing ruby
For example: libyaml-devel
=> Add a note for CentOS 8

README.md
Add Backport Process and Sprint Boundaries pointers.
=> Update README.md (backport process and sprint boundaries

triage_process.md
@chessbyte Please review.
cc @ManageIQ/core-triage
=> Add links for backport triage of jansa/yes? issues

mergers_guidelines.md
Added a note about creating a merge commit. Also removed setting a milestone.
=> Merger "DO" update for merge commit and milestone

mergers_guidelines.md
=> Cleanup merger guidelines

architecture/logging.md
@chessbyte Please review.
~~Only thing I'm not sure about is the json format...need some examples from those who've run podified / containers.~~ EDIT: got some examples...thanks @agrare
=> Add documentation for logging

bin/generate_triage_links.rb, bin/triage.yml, triage_process.md
@chessbyte Please review.
Closes #418
=> Consolidate triage meetings

triage_process.md
=> Change triage ordering

.rubocop_base.yml
=> Disable Style/AccessModifierDeclarations

i18n.md
=> Update i18n.md to replace Zanata with Transifex

architecture/plugins.md
Add a description of plugin with a list of what is "pluggable" and short
description of plugin vs provider plugin
=> Add a guide article about plugins

developer_setup.md
=> Update the minimum NodeJS version to 12

developer_setup/plugins.md
@chessbyte Please review
This information is no longer needed since nobody really needs to transfer UI PRs in core to the ui-classic plugin anymore.
=> Remove outdated info for transferring PRs

developer_setup.md
Prefer tables where we can in order to guide a reader's eyes directly to
the information they need instead of needing to read the entire section
which is overwhelming.
Before: https://github.com/ManageIQ/guides/blob/13e735fcb48c5a4f808f9bc85e413b54664061be/developer_setup.md#new-developer-setup
After: https://github.com/ManageIQ/guides/blob/52a4905eddbf3facbacf516d14943f2dc968a931/developer_setup.md#new-developer-setup
@chessbyte Please review
=> Cleanup developer setup

developer_setup.md
Depends on https://github.com/ManageIQ/manageiq/pull/21052
=> Remove sqlite

developer_setup.md
Update developer setup for 2.6+ per ManageIQ/manageiq#19678
=> Update developer setup for 2.6+ per ManageIQ/manageiq#19678.

developer_setup.md
Reviewing these steps with some new developers, I found some things lacking or unclear, so this PR fixes those.
@chessbyte Please review.  (easier to review with whitespace diffs off)
=> Various dev setup updates

developer_setup.md
add ManageIQ Bot info in developer_set.md Further Reading section
=> Add ManageIQ Bot info to developer_setup.md

providers/targeted_refresh.md, providers/writing_a_new_provider.md
A follow-up to the `Writing a provider from scratch`, a quick guide on how to add targeted refresh to your provider.
=> Add a simple targeted refresh getting started guide

external_auth/realms/ManageIQ-realm.json
=> Add ext auth users with many groups

README.md, logical_replication_migrations.md
From discussion and testing mentioned in https://github.com/ManageIQ/manageiq/pull/21259
=> Add guide on testing logical replication with migrations

labels.md
Will be handle with css where needed.
Links
-----
- Merge with https://github.com/ManageIQ/manageiq.org/pull/1021
=> [labels.md] Remove </br> tags

vagrant_developer_vm.md
Fedora & Ruby versions, along with cosmetic formating.
Signed-off-by: Hiro Miyamoto <miyamotoh@us.ibm.com>
=> Refresh for Fedora 33 & Ruby 2.6.5

providers/targeted_refresh.md
=> Move add_target and references to core collector

providers/create_operation.md
Hi
Is this appropriate for the guides repository?
It's a guide on where to add what code to enable creation of an externally managed item in your EMS.
* Need to determine location and name of file.
=> Create button guide

i18n.md
Fix i18n docs
@miq-bot add-label bug
@miq-bot add_reviewer @Fryguy
=> Fix Ii8n docs for service ui

developer_setup.md
Update node version to 16
Issue:https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq-bot add_reviewer @Fryguy 
@miq-bot add-label dependencies
=> Update node version

developer_setup.md
Issue: https://github.com/ManageIQ/manageiq-ui-classic/issues/7930
@miq_bot assign @fryguy
@miq_bot add_reviewer @fryguy
@miq_bot add-label dependencies, najdorf/yes?
=> Downgrade node version to 14

developer_setup.md
Also remove Rails because it's not an pre-install dep, but will be installed automatically.
@agrare @jrafanie Please review.
=> Update dev setup minimums

developer_setup.md, vagrant_developer_vm.md
The ManageIQ project has recently added Ruby 3.0 support and dropped Ruby 2.6 support.
See https://github.com/ManageIQ/manageiq/discussions/22120
=> Update guides to show support for Ruby 2.7 and 3.0

providers/adding_a_new_model.md, providers/writing_a_new_provider.md
Follow-ups to https://github.com/ManageIQ/guides/pull/509
* Change AutoSDE to AwesomeCloud to keep consistent with the rest of the
`writing_a_new_provider` series.
* Replace "copy from miq vm" with a more standard dev workflow
=> Some follow-ups to the `adding_a_new_model` guide

.github/workflows/ci.yaml
=> Fix website build token

developer_setup.md
Upgrading node version from **14.0.0 to 18.0.0**
Fixes - https://github.com/ManageIQ/manageiq-ui-classic/issues/8690
=> Upgrade Node v14 to v18

developer_setup.md
Upgrade `Node 14` to `Node 16`
Previous - https://github.com/ManageIQ/guides/pull/479
Fixes - https://github.com/ManageIQ/manageiq-ui-classic/issues/8146
=> [WIP] Upgrade Node v14 to v16

external_auth/ipa.md
As suggested in:
https://github.com/ManageIQ/manageiq-appliance_console/pull/211
=> Add information on the demo ipa server

developer_setup.md
=> Drop CentOS 8 setup steps

developer_setup.md
This is partially dependent on https://github.com/ManageIQ/manageiq/pull/23008, but we can merge them independently.
=> Update dev versions

developer_setup.md
Followup to: https://github.com/ManageIQ/manageiq/pull/23204
=> Ruby 3.2 and 3.3 support is in the works

.github/workflows/ci.yaml
Follow up to ManageIQ/manageiq.org#1192
=> Upgrade Ruby to 3.3

providers/writing_vcr_specs.md
Follow up to https://github.com/ManageIQ/manageiq/pull/23496
@agrare Please review.
=> Update VCR guide for the new VcrSecrets helper

providers/events.md, providers/subclassing_an_existing_provider.md, providers/targeted_refresh.md, providers/writing_a_new_provider.md
Ref https://github.com/ManageIQ/manageiq-providers-nutanix/pull/12#issuecomment-3032899700, https://github.com/ManageIQ/manageiq/pull/23505
=> Drop require_nested from providers guides
